routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->name('welcome');

Auth::routes();

// Change Password Routes
Route::get('change-password', 'Auth\ChangePasswordController@show')->name('password.change');
Route::patch('change-password', 'Auth\ChangePasswordController@update')->name('password.change');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/home', 'TransactionsController@index')->name('home');

    /*
     * Transactions Routes
     */
    Route::resource('transactions', 'TransactionsController');

    /*
     * Categories Routes
     */
    Route::resource('categories', 'CategoriesController');

    /*
     * Report Routes
     */
    Route::get('/report', 'ReportsController@index')->name('reports.index');
});

resources/views/layouts/partials/noty.blade.php
@if(Session::has('flash_notification.message'))
@php
    $level = Session::get('flash_notification.level');
    if ($level == 'info') {
        $level = 'information';
    }
@endphp
<script src="{{ asset('js/plugins/noty.js') }}"></script>
<script>
    noty({
        type: '{{ $level }}',
        layout: 'bottomRight',
        text: '{{ Session::get('flash_notification.message') }}',
        timeout: 3000
    });
</script>
@endif

resources/views/layouts/partials/top-nav.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ route('home') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
        </div>

        <!-- Right Side Of Navbar -->
        <div class="nav navbar-nav navbar-right" style="margin: 0;">
            <!-- Authentication Links -->
            @guest
                {{ link_to_route('login', __('auth.login'), [], ['class' => 'xs-navbar']) }}
                {{ link_to_route('register', __('auth.register'), [], ['class' => 'xs-navbar']) }}
            @else
                <a class="xs-navbar" href="{{ route('transactions.index') }}" title="{{ __('transaction.transaction') }}">
                    <span class="glyphicon glyphicon-retweet" aria-hidden="true"></span>&nbsp;
                    <span class="hidden-xs">{{ __('transaction.transaction') }}</span>
                </a>
                <a class="xs-navbar" href="{{ route('reports.index') }}" title="{{ __('report.report') }}">
                    <span class="glyphicon glyphicon-equalizer" aria-hidden="true"></span>&nbsp;
                    <span class="hidden-xs">{{ __('report.report') }}</span>
                </a>
                <a class="xs-navbar" href="{{ route('categories.index') }}" title="{{ __('category.category') }}">
                    <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>&nbsp;
                    <span class="hidden-xs">{{ __('category.category') }}</span>
                </a>
                <a class="xs-navbar" href="{{ route('password.change') }}" title="{{ __('auth.change_password') }}">
                    <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>&nbsp;
                    <span class="hidden-xs">{{ __('auth.change_password') }}</span>
                </a>
                <a class="xs-navbar" href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                             document.getElementById('logout-form').submit();">
                    <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    <input type="submit" value="{{ __('auth.logout') }}" style="display: none;">
                    {{ csrf_field() }}
                </form>
            @endguest
        </div>
    </div>
</nav>